/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ood.borobicycles;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.ArrayList;

/**
 *
 * @author okafo
 */
public class GUI extends javax.swing.JFrame {

    // Specifies the delimiter for file reading
    private static final String DELIMITER = ",";
    // the location of bicycles.txt file
    private static final String RELATIVE_PATH = "data/bicycles.txt";
    static ArrayList<Bicycle> bicycleList = new ArrayList<>();
    static Scanner sc = new Scanner(System.in);

    // method to load bicycle data into table with exeption handling capabities
    public static void loadBicycles() throws IOException, FileNotFoundException {

        // File object used to read from file
        File inputFile = new File(RELATIVE_PATH);

        // Checks if the file path is good and that it is a file
        if (inputFile.exists() && inputFile.isFile()) {

            // Scanner object to read from file
            Scanner fileScanner = new Scanner(inputFile);

            //Process file
            while (fileScanner.hasNextLine()) {
                // read each line
                String line = fileScanner.nextLine().trim();
                if (!line.isEmpty()) {
                    //process line assigning each part to the respective variable 
                    String sku = line.split(DELIMITER)[0];
                    double price = Double.parseDouble(line.split(DELIMITER)[1]);
                    String make = line.split(DELIMITER)[2];
                    String model = line.split(DELIMITER)[3];
                    String colour = line.split(DELIMITER)[4];
                    String ageRange = line.split(DELIMITER)[5];
                    String material = line.split(DELIMITER)[6];
                    String feature = line.split(DELIMITER)[7];
                    int quantity = Integer.parseInt(line.split(DELIMITER)[8]);
                    boolean assembled = Boolean.parseBoolean(line.split(DELIMITER)[9]);
                    bicycleList.add(new Bicycle(sku, price, make, model, colour, ageRange, material, feature, quantity, assembled));
                }
            }// End of While loop

            // close file Stream
            fileScanner.close();
        }
    }

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

        // load bicycle data
        try {
            loadBicycles();
            if (bicycleList.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No data found. Please check the file and restart.");
                System.exit(0);

            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace(); // or show a dialog to the user
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
